ACQ-953: Added metrics scraping for membership-events svc
Financial-Times/next-metrics pull request #420
Opened 2021-07-05 14:32 UTC by PlamenHristov

@ludrob, as [requested](https://financialtimes.atlassian.net/browse/ACQ-953?focusedCommentId=520313)

2021-07-05 14:52 UTC, ludrob commented on lib/metrics/services.js
> +	'membership-events-test': /^https:\/\/api-t\.ft\.com\/events\/.*/,
Unless I am mistaken we do a fetch on: 
https://api.bizzabo.com/api/events

Vault variable:
BIZZABO_API_URL_PROD: https://api.bizzabo.com/api
(or does this need to be updated to use membership endpoints?)

From next-subscribe here: 
https://github.com/Financial-Times/next-subscribe/blob/main/server/helpers/bizzabo.js#L21

```
const res = await fetch(`${this.config.apiUrl}/events/${eventId}`, {
			method: 'GET',
			headers: {
				Authorization: `Bearer ${this.config.apiKey}`,
				Accept: 'application/vnd.bizzabo.v2.0+json',
			},
		});
```

2021-07-05 14:56 UTC, ludrob requested changes
I think there is some mix up with the urls?

2021-12-14 14:30 UTC, ststdimov commented on lib/metrics/services.js
> +	'membership-events-test': /^https:\/\/api-t\.ft\.com\/events\/.*/,
So I know it's been a long time on this PR.

If we're using a particular API url through a dependency (like https://api.ft.com/events/bizzaboo/register is used through the membership lib) - we should **not** add it to lib/metrics/services.js. Correct ?
On the other hand we should add https://api.bizzabo.com/api/events because it's used directly 

OR 

We should both https://api.bizzabo.com/api and https://api.ft.com/events/bizzaboo/register ?

2021-12-16 11:52 UTC, ludrob commented on lib/metrics/services.js
> +	'membership-events-test': /^https:\/\/api-t\.ft\.com\/events\/.*/,
I think we almost good just need to add this one: https://api.ft.com/events/bizzaboo/register

It's fetched through membership-sdk.
Which is just a component that gets baked in next-subscribe.
So technically speaking, it's next-subscribe doing the fetch.

2021-12-16 12:47 UTC, ludrob commented on lib/metrics/services.js
> +	'bizzabo-register': /^https:\/\/api.ft.com\/events\/bizzaboo\/register/,
```suggestion
	'bizzabo-register': /^https:\/\/api\.ft\.com\/events\/bizzaboo\/register/,
```

2021-12-16 12:53 UTC, ludrob approved these changes

2021-12-16 12:55 UTC, valeksiev approved these changes

2021-12-16 12:56 UTC, merged